namespace TrackBoard.Entities;

public enum TrackType
{
    Circuit,
    Sprint,
}

public enum TrackVisibility
{
    Private,
    Published,
}

/// <summary>Anything a single user owns outright. Ownership is enforced by resource authorization.</summary>
public interface IOwnedResource
{
    Guid OwnerId { get; }
}

/// <summary>
/// A track as built in TrackPro's Track Builder. The id is generated by the app, so a
/// retried upload lands on the same row.
/// </summary>
public class Track : BaseEntity, IOwnedResource
{
    public Guid OwnerId { get; set; }

    public User Owner { get; set; } = null!;

    public string Name { get; set; } = string.Empty;

    public string Country { get; set; } = string.Empty;

    public TrackType Type { get; set; }

    public double? LengthMeters { get; set; }

    public TrackVisibility Visibility { get; set; } = TrackVisibility.Private;

    /// <summary>
    /// Denormalised from <see cref="Points"/> on every write, so a "tracks near me" search
    /// can filter in SQL without loading any geometry.
    /// </summary>
    public double? StartLatitude { get; set; }

    /// <inheritdoc cref="StartLatitude"/>
    public double? StartLongitude { get; set; }

    /// <summary>Number of points flagged as sector gates. Denormalised like the start point.</summary>
    public int SectorCount { get; set; }

    /// <summary>
    /// The ordered centre line. TrackPro derives its start, finish and sector gates from this
    /// list on the device, so its order and flags are the timing contract.
    /// </summary>
    public ICollection<TrackPoint> Points { get; set; } = [];

    public ICollection<Session> Sessions { get; set; } = [];
}

/// <summary>
/// One TrackPro <c>TrackCoordinatesData</c> row. Keyed by (track, position) rather than a
/// surrogate id: a track can carry thousands of these, and they are only ever replaced as a set.
/// </summary>
public class TrackPoint
{
    public Guid TrackId { get; set; }

    /// <summary>Position in the ordered list, from zero.</summary>
    public int Seq { get; set; }

    public double Latitude { get; set; }

    public double Longitude { get; set; }

    /// <summary>Metres.</summary>
    public double? Altitude { get; set; }

    public bool IsStartPoint { get; set; }

    public bool IsSectorPoint { get; set; }

    public int? SectorIndex { get; set; }
}
