// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackBoard.Data;

#nullable disable

namespace TrackBoard.Data.Migrations
{
    [DbContext(typeof(TrackBoardDbContext))]
    partial class TrackBoardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrackBoard.Entities.Circuit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ElevationChangeMeters")
                        .HasColumnType("integer")
                        .HasColumnName("elevation_change_meters");

                    b.Property<int>("LengthMeters")
                        .HasColumnType("integer")
                        .HasColumnName("length_meters");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("Turns")
                        .HasColumnType("integer")
                        .HasColumnName("turns");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_circuits");

                    b.HasIndex("Country")
                        .HasDatabaseName("ix_circuits_country");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_circuits_name");

                    b.ToTable("circuits", (string)null);
                });

            modelBuilder.Entity("TrackBoard.Entities.PointsScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("FastestLapBonus")
                        .HasColumnType("integer")
                        .HasColumnName("fastest_lap_bonus");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("PolePositionBonus")
                        .HasColumnType("integer")
                        .HasColumnName("pole_position_bonus");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_points_schemes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_points_schemes_name");

                    b.ToTable("points_schemes", (string)null);
                });

            modelBuilder.Entity("TrackBoard.Entities.PointsSchemeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<Guid>("PointsSchemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("points_scheme_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_points_scheme_entries");

                    b.HasIndex("PointsSchemeId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_points_scheme_entries_points_scheme_id_position");

                    b.ToTable("points_scheme_entries", (string)null);
                });

            modelBuilder.Entity("TrackBoard.Entities.RaceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CircuitId")
                        .HasColumnType("uuid")
                        .HasColumnName("circuit_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Laps")
                        .HasColumnType("integer")
                        .HasColumnName("laps");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_race_events");

                    b.HasIndex("CircuitId")
                        .HasDatabaseName("ix_race_events_circuit_id");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_race_events_series_id");

                    b.HasIndex("SeriesId", "ScheduledAt")
                        .HasDatabaseName("ix_race_events_series_id_scheduled_at");

                    b.ToTable("race_events", (string)null);
                });

            modelBuilder.Entity("TrackBoard.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TrackBoard.Entities.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("BestLapTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("best_lap_time_ms");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DidNotFinish")
                        .HasColumnType("boolean")
                        .HasColumnName("did_not_finish");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int?>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("RaceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("race_event_id");

                    b.Property<bool>("SetFastestLap")
                        .HasColumnType("boolean")
                        .HasColumnName("set_fastest_lap");

                    b.Property<bool>("StartedFromPole")
                        .HasColumnType("boolean")
                        .HasColumnName("started_from_pole");

                    b.Property<long?>("TotalTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("total_time_ms");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_results");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_results_user_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_results_vehicle_id");

                    b.HasIndex("RaceEventId", "Position")
                        .HasDatabaseName("ix_results_race_event_id_position");

                    b.HasIndex("RaceEventId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_results_race_event_id_user_id");

                    b.ToTable("results", (string)null);
                });

            modelBuilder.Entity("TrackBoard.Entities.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("PointsSchemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("points_scheme_id");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_series");

                    b.HasIndex("PointsSchemeId")
                        .HasDatabaseName("ix_series_points_scheme_id");

                    b.HasIndex("Season")
                        .HasDatabaseName("ix_series_season");

                    b.HasIndex("Name", "Season")
                        .IsUnique()
                        .HasDatabaseName("ix_series_name_season");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("TrackBoard.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TrackBoard.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("Acceleration")
                        .HasColumnType("double precision")
                        .HasColumnName("acceleration");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Drivetrain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("drivetrain");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("engine_type");

                    b.Property<double?>("FuelCapacity")
                        .HasColumnType("double precision")
                        .HasColumnName("fuel_capacity");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fuel_type");

                    b.Property<int>("Horsepower")
                        .HasColumnType("integer")
                        .HasColumnName("horsepower");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("SuspensionType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("suspension_type");

                    b.Property<string>("TireType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tire_type");

                    b.Property<double?>("TopSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("top_speed");

                    b.Property<int?>("Torque")
                        .HasColumnType("integer")
                        .HasColumnName("torque");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transmission");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_vehicles_owner_id");

                    b.HasIndex("Manufacturer", "Model")
                        .HasDatabaseName("ix_vehicles_manufacturer_model");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("TrackBoard.Entities.PointsSchemeEntry", b =>
                {
                    b.HasOne("TrackBoard.Entities.PointsScheme", "PointsScheme")
                        .WithMany("Entries")
                        .HasForeignKey("PointsSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_points_scheme_entries_points_schemes_points_scheme_id");

                    b.Navigation("PointsScheme");
                });

            modelBuilder.Entity("TrackBoard.Entities.RaceEvent", b =>
                {
                    b.HasOne("TrackBoard.Entities.Circuit", "Circuit")
                        .WithMany("RaceEvents")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_race_events_circuits_circuit_id");

                    b.HasOne("TrackBoard.Entities.Series", "Series")
                        .WithMany("RaceEvents")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_race_events_series_series_id");

                    b.Navigation("Circuit");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("TrackBoard.Entities.RefreshToken", b =>
                {
                    b.HasOne("TrackBoard.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackBoard.Entities.Result", b =>
                {
                    b.HasOne("TrackBoard.Entities.RaceEvent", "RaceEvent")
                        .WithMany("Results")
                        .HasForeignKey("RaceEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_results_race_events_race_event_id");

                    b.HasOne("TrackBoard.Entities.User", "User")
                        .WithMany("Results")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_results_users_user_id");

                    b.HasOne("TrackBoard.Entities.Vehicle", "Vehicle")
                        .WithMany("Results")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_results_vehicles_vehicle_id");

                    b.Navigation("RaceEvent");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TrackBoard.Entities.Series", b =>
                {
                    b.HasOne("TrackBoard.Entities.PointsScheme", "PointsScheme")
                        .WithMany("Series")
                        .HasForeignKey("PointsSchemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_series_points_schemes_points_scheme_id");

                    b.Navigation("PointsScheme");
                });

            modelBuilder.Entity("TrackBoard.Entities.Vehicle", b =>
                {
                    b.HasOne("TrackBoard.Entities.User", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TrackBoard.Entities.Circuit", b =>
                {
                    b.Navigation("RaceEvents");
                });

            modelBuilder.Entity("TrackBoard.Entities.PointsScheme", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("TrackBoard.Entities.RaceEvent", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("TrackBoard.Entities.Series", b =>
                {
                    b.Navigation("RaceEvents");
                });

            modelBuilder.Entity("TrackBoard.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Results");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("TrackBoard.Entities.Vehicle", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
